/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.36.            *
*        Compiled Aug 31 2016, 09:25:09                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: bmp_work_on                                           *
* Dimensions:  16 * 16                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmp_work_on;

static GUI_CONST_STORAGE unsigned long _acbmp_work_on[] = {
  0xFF000000, 0xFF000000, 0xFF000000, 0xF8000000, 0xE3000000, 0xD2000000, 0xC4000000, 0xBC000000, 0xBC000000, 0xC4000000, 0xD2000000, 0xE3000000, 0xF8000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xED000000, 0xD8000000, 0xB5000000, 0x58000000, 0x20000000, 0x05000000, 0x05000000, 0x22000000, 0x5B000000, 0xB5000000, 0xD8000000, 0xED000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xEF000000, 0xD9000000, 0x85000000, 0x0B000000, 0x00010101, 0x00020202, 0x00030303, 0x00030303, 0x00030303, 0x00030303, 0x0B020202, 0x85010101, 0xD9000000, 0xEF000000, 0xFF000000,
  0xF7000000, 0xE2000000, 0x8C000000, 0x01000000, 0x00020202, 0x00061F03, 0x000D5F02, 0x00107E00, 0x000D6F00, 0x000A4403, 0x00081706, 0x00070707, 0x01040404, 0x8C010101, 0xE2000000, 0xF7000000,
  0xEF000000, 0xC9000000, 0x0C000000, 0x00020202, 0x00093503, 0x00129300, 0x0017B600, 0x0016AE00, 0x00129800, 0x000E7800, 0x000A5600, 0x00092106, 0x000A0A0A, 0x0C060606, 0xC8010101, 0xEF000000,
  0xEC000000, 0x6D000000, 0x00020202, 0x00071904, 0x000E7B00, 0x0014A500, 0x0016B100, 0x0014A900, 0x00119400, 0x000F7C00, 0x000B6300, 0x00074400, 0x000A1609, 0x000B0B0B, 0x69050505, 0xEB000000,
  0xED000000, 0x2A010101, 0x00040404, 0x00093E02, 0x000F7C00, 0x00119400, 0x00129A00, 0x00119400, 0x00108400, 0x000D7100, 0x000A5D00, 0x00084A00, 0x00082D04, 0x000D0D0D, 0x290A0A0A, 0xED000000,
  0xF2000000, 0x07020202, 0x00070707, 0x00094901, 0x000D6F00, 0x000F7C00, 0x000F8000, 0x000F7C00, 0x000D7100, 0x000B6200, 0x00095400, 0x00084E00, 0x00063B01, 0x000E0E0E, 0x060C0C0C, 0xF2000000,
  0xF8000000, 0x07030303, 0x00090909, 0x00073F01, 0x000A5C00, 0x000B6500, 0x000C6700, 0x000B6500, 0x000A5D00, 0x00095400, 0x00084F00, 0x00084E00, 0x00063B01, 0x000E0E0E, 0x0C0D0D0D, 0xF8000000,
  0xFEFFFFFF, 0x2F030303, 0x000A0A0A, 0x00082D03, 0x00084A00, 0x00095200, 0x00095400, 0x00095200, 0x00084F00, 0x00084F00, 0x00084F00, 0x00084A00, 0x00082D04, 0x000E0E0E, 0x2E0E0E0E, 0xFF000000,
  0xF5FFFFFF, 0x790B0B0B, 0x000A0A0A, 0x000B170A, 0x00074200, 0x00084D00, 0x00084F00, 0x00084F00, 0x00084F00, 0x00084F00, 0x00084D00, 0x00074200, 0x000B170A, 0x000E0E0E, 0x75151515, 0xF6FFFFFF,
  0xF2FFFFFF, 0xD96D6D6D, 0x0D0A0A0A, 0x000D0D0D, 0x00092107, 0x00074200, 0x00084A00, 0x00084E00, 0x00084E00, 0x00084A00, 0x00074200, 0x00092106, 0x000E0E0E, 0x0D0F0F0F, 0xD9737373, 0xF2FFFFFF,
  0xFCFFFFFF, 0xEAFFFFFF, 0x99353535, 0x010C0C0C, 0x000E0E0E, 0x000B170A, 0x00082D04, 0x00063B01, 0x00063B01, 0x00082D04, 0x000B170A, 0x000E0E0E, 0x010E0E0E, 0x993A3A3A, 0xEAFFFFFF, 0xFCFFFFFF,
  0xFF000000, 0xF3FFFFFF, 0xE2FFFFFF, 0x91444444, 0x0B0F0F0F, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x0B101010, 0x92484848, 0xE2FFFFFF, 0xF3FFFFFF, 0xFF000000,
  0xFF000000, 0xFF000000, 0xF2FFFFFF, 0xDFFFFFFF, 0xC2AFAFAF, 0x61323232, 0x23171717, 0x040F0F0F, 0x09101010, 0x27191919, 0x63353535, 0xC2B0B0B0, 0xDFFFFFFF, 0xF3FFFFFF, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFCFFFFFF, 0xE5FFFFFF, 0xD9FFFFFF, 0xCFFFFFFF, 0xCBFFFFFF, 0xCBFFFFFF, 0xD0FFFFFF, 0xD9FFFFFF, 0xE6FFFFFF, 0xFCFFFFFF, 0xFF000000, 0xFF000000, 0xFF000000
};

GUI_CONST_STORAGE GUI_BITMAP bmp_work_on = {
  16, // xSize
  16, // ySize
  64, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acbmp_work_on,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
