/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Bitmap Converter for emWin (Demo version) V5.36.            *
*        Compiled Aug 31 2016, 09:25:09                              *
*                                                                    *
*        (c) 1998 - 2016 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
*        May not be used in a product                                *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: bmp_work_off                                          *
* Dimensions:  16 * 16                                               *
* NumColors:   32bpp: 16777216 + 256                                 *
*                                                                    *
**********************************************************************
*/

#include <stdlib.h>

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

extern GUI_CONST_STORAGE GUI_BITMAP bmp_work_off;

static GUI_CONST_STORAGE unsigned long _acbmp_work_off[] = {
  0xFF000000, 0xFF000000, 0xFF000000, 0xF8000000, 0xE3000000, 0xD2000000, 0xC4000000, 0xBC000000, 0xBC000000, 0xC4000000, 0xD2000000, 0xE3000000, 0xF8000000, 0xFF000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xED000000, 0xD8000000, 0xB5000000, 0x58000000, 0x20000000, 0x05000000, 0x05000000, 0x22000000, 0x5B000000, 0xB5000000, 0xD8000000, 0xED000000, 0xFF000000, 0xFF000000,
  0xFF000000, 0xEF000000, 0xD9000000, 0x85000000, 0x0B000000, 0x00010101, 0x00020202, 0x00030303, 0x00030303, 0x00030303, 0x00030303, 0x0B020202, 0x85010101, 0xD9000000, 0xEF000000, 0xFF000000,
  0xF7000000, 0xE2000000, 0x8C000000, 0x01000000, 0x00020202, 0x00111111, 0x00313131, 0x00404040, 0x00373737, 0x00222222, 0x000E0E0E, 0x00070707, 0x01040404, 0x8C010101, 0xE2000000, 0xF7000000,
  0xEF000000, 0xC9000000, 0x0C000000, 0x00020202, 0x001C1C1C, 0x004B4B4B, 0x005D5D5D, 0x00595959, 0x004C4C4C, 0x003A3A3A, 0x00282828, 0x00121212, 0x000A0A0A, 0x0C060606, 0xC8010101, 0xEF000000,
  0xEC000000, 0x6D000000, 0x00020202, 0x000E0E0E, 0x003E3E3E, 0x00535353, 0x005A5A5A, 0x00555555, 0x004A4A4A, 0x003C3C3C, 0x002E2E2E, 0x001F1F1F, 0x000F0F0F, 0x000B0B0B, 0x69050505, 0xEB000000,
  0xED000000, 0x2A010101, 0x00040404, 0x001F1F1F, 0x003D3D3D, 0x004A4A4A, 0x004D4D4D, 0x004A4A4A, 0x00414141, 0x00363636, 0x002B2B2B, 0x00212121, 0x00151515, 0x000D0D0D, 0x290A0A0A, 0xED000000,
  0xF2000000, 0x07020202, 0x00070707, 0x00222222, 0x00353535, 0x003C3C3C, 0x003E3E3E, 0x003C3C3C, 0x00363636, 0x002D2D2D, 0x00262626, 0x00222222, 0x001A1A1A, 0x000E0E0E, 0x060C0C0C, 0xF2000000,
  0xF8000000, 0x07030303, 0x00090909, 0x001D1D1D, 0x002A2A2A, 0x002F2F2F, 0x00303030, 0x002F2F2F, 0x002B2B2B, 0x00262626, 0x00232323, 0x00222222, 0x001A1A1A, 0x000E0E0E, 0x0C0D0D0D, 0xF8000000,
  0xFEFFFFFF, 0x2F030303, 0x000A0A0A, 0x00161616, 0x00212121, 0x00252525, 0x00262626, 0x00252525, 0x00232323, 0x00232323, 0x00232323, 0x00212121, 0x00151515, 0x000E0E0E, 0x2E0E0E0E, 0xFF000000,
  0xF5FFFFFF, 0x790B0B0B, 0x000A0A0A, 0x00101010, 0x001D1D1D, 0x00222222, 0x00232323, 0x00232323, 0x00232323, 0x00232323, 0x00222222, 0x001D1D1D, 0x00101010, 0x000E0E0E, 0x75151515, 0xF6FFFFFF,
  0xF2FFFFFF, 0xD96D6D6D, 0x0D0A0A0A, 0x000D0D0D, 0x00121212, 0x001D1D1D, 0x00212121, 0x00222222, 0x00222222, 0x00212121, 0x001D1D1D, 0x00121212, 0x000E0E0E, 0x0D0F0F0F, 0xD9737373, 0xF2FFFFFF,
  0xFCFFFFFF, 0xEAFFFFFF, 0x99353535, 0x010C0C0C, 0x000E0E0E, 0x00101010, 0x00151515, 0x001A1A1A, 0x001A1A1A, 0x00151515, 0x00101010, 0x000E0E0E, 0x010E0E0E, 0x993A3A3A, 0xEAFFFFFF, 0xFCFFFFFF,
  0xFF000000, 0xF3FFFFFF, 0xE2FFFFFF, 0x91444444, 0x0B0F0F0F, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x000E0E0E, 0x0B101010, 0x92484848, 0xE2FFFFFF, 0xF3FFFFFF, 0xFF000000,
  0xFF000000, 0xFF000000, 0xF2FFFFFF, 0xDFFFFFFF, 0xC2AFAFAF, 0x61323232, 0x23171717, 0x040F0F0F, 0x09101010, 0x27191919, 0x63353535, 0xC2B0B0B0, 0xDFFFFFFF, 0xF3FFFFFF, 0xFF000000, 0xFF000000,
  0xFF000000, 0xFF000000, 0xFF000000, 0xFCFFFFFF, 0xE5FFFFFF, 0xD9FFFFFF, 0xCFFFFFFF, 0xCBFFFFFF, 0xCBFFFFFF, 0xD0FFFFFF, 0xD9FFFFFF, 0xE6FFFFFF, 0xFCFFFFFF, 0xFF000000, 0xFF000000, 0xFF000000
};

GUI_CONST_STORAGE GUI_BITMAP bmp_work_off = {
  16, // xSize
  16, // ySize
  64, // BytesPerLine
  32, // BitsPerPixel
  (unsigned char *)_acbmp_work_off,  // Pointer to picture data
  NULL,  // Pointer to palette
  GUI_DRAW_BMP8888
};

/*************************** End of file ****************************/
