#!/usr/bin/python
# -*- coding: utf-8 -*-

import os

from config_build_common import build_common_config 

env = DefaultEnvironment();

cur_build_path = Dir('.',False);

InstallDir(build_common_config.AW_SDK_INSTALL_PATH+'/apollo/interface',str(cur_build_path.srcnode()) )
